services:
  # Backend
  # Laravel
  app:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    container_name: tedexis_laravel_app
    restart: unless-stopped
    volumes:
      - ./Backend:/var/www
    networks:
      - laravel
      
  # Frontend Angular
  # Angular
  angular:
    build:
      context: ./Frontend
    container_name: tedexis_angular_app
    restart: unless-stopped
    command: ng serve --host 0.0.0.0 --port 4200
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend:/usr/src/app
    networks:
      - laravel



  # Servidor Web
  # Nginx
  nginx:
    image: nginx:1.25
    container_name: tedexis_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./Backend:/var/www
      - ./nginx/conf.d/app.config:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: tedexis_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_tedexis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jg081101
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel
    ports:
      - "5433:5432"

  # Base de datos MongoDB
  mongodb:
    image: mongo:7.0
    container_name: tedexis_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-app}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - laravel

  # Redis para cache y colas
  redis:
    image: redis:7-alpine
    container_name: tedexis_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  pgdata:
